In [9]:
import numpy as np
import pandas as pd

In [10]:
import matplotlib.pyplot as plt

In [11]:
from sklearn.linear_model import LinearRegression
regress = LinearRegression()

In [12]:
data = pd.read_excel("DataBase Age Vs B.P.xlsx")

In [13]:
x=np.array(data['AGE'])
y=np.array(data['Blood pressur(B.P)'])
x=x.reshape(-1,1)
y=y.reshape(-1,1)
regress.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
x

array([[39],
       [47],
       [45],
       [47],
       [65],
       [46],
       [67],
       [42],
       [67],
       [56],
       [64],
       [56],
       [59],
       [34],
       [42],
       [48],
       [45],
       [17],
       [20],
       [19],
       [36],
       [50],
       [39],
       [21],
       [44],
       [53],
       [63],
       [29],
       [25],
       [69]], dtype=int64)

In [15]:
y

array([[144],
       [220],
       [138],
       [145],
       [162],
       [142],
       [170],
       [124],
       [158],
       [154],
       [162],
       [150],
       [140],
       [110],
       [128],
       [130],
       [135],
       [114],
       [116],
       [124],
       [136],
       [142],
       [120],
       [120],
       [160],
       [158],
       [144],
       [130],
       [125],
       [175]], dtype=int64)

In [17]:
x=int(input("Enter Age :"))
x=np.array(x).reshape(-1,1)
regress.predict(x)

Enter Age :15


array([[113.27777341]])